version: '3.8'
services:
  backend:
    build: ./task-manager-backend
    ports:
      - '3000:3000'
    links:
      - db
    depends_on:
      - db
    volumes:
      - ./task-manager-backend:/app

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: task_manager
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql

  frontend:
    build: ./task-manager-frontend
    ports:
      - '8080:80'
    depends_on:
      - backend

volumes:
  db_data: